package hibernate;
// Generated 19-jun-2013 14:01:36 by Hibernate Tools 3.2.1.GA



/**
 * CuentasHasClientesId generated by hbm2java
 */
public class CuentasHasClientesId  implements java.io.Serializable {


     private int cuentasPkCuenta;
     private int clientesPkCliente;

    public CuentasHasClientesId() {
    }

    public CuentasHasClientesId(int cuentasPkCuenta, int clientesPkCliente) {
       this.cuentasPkCuenta = cuentasPkCuenta;
       this.clientesPkCliente = clientesPkCliente;
    }
   
    public int getCuentasPkCuenta() {
        return this.cuentasPkCuenta;
    }
    
    public void setCuentasPkCuenta(int cuentasPkCuenta) {
        this.cuentasPkCuenta = cuentasPkCuenta;
    }
    public int getClientesPkCliente() {
        return this.clientesPkCliente;
    }
    
    public void setClientesPkCliente(int clientesPkCliente) {
        this.clientesPkCliente = clientesPkCliente;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CuentasHasClientesId) ) return false;
		 CuentasHasClientesId castOther = ( CuentasHasClientesId ) other; 
         
		 return (this.getCuentasPkCuenta()==castOther.getCuentasPkCuenta())
 && (this.getClientesPkCliente()==castOther.getClientesPkCliente());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCuentasPkCuenta();
         result = 37 * result + this.getClientesPkCliente();
         return result;
   }   


}


