package hibernate;
// Generated 19-jun-2013 14:01:36 by Hibernate Tools 3.2.1.GA



/**
 * Domiciliaciones generated by hbm2java
 */
public class Domiciliaciones  implements java.io.Serializable {


     private Integer pkDomiciliacion;
     private Cuentas cuentas;
     private String entidad;
     private boolean bloqueado;

    public Domiciliaciones() {
    }

    public Domiciliaciones(Cuentas cuentas, String entidad, boolean bloqueado) {
       this.cuentas = cuentas;
       this.entidad = entidad;
       this.bloqueado = bloqueado;
    }
   
    public Integer getPkDomiciliacion() {
        return this.pkDomiciliacion;
    }
    
    public void setPkDomiciliacion(Integer pkDomiciliacion) {
        this.pkDomiciliacion = pkDomiciliacion;
    }
    public Cuentas getCuentas() {
        return this.cuentas;
    }
    
    public void setCuentas(Cuentas cuentas) {
        this.cuentas = cuentas;
    }
    public String getEntidad() {
        return this.entidad;
    }
    
    public void setEntidad(String entidad) {
        this.entidad = entidad;
    }
    public boolean isBloqueado() {
        return this.bloqueado;
    }
    
    public void setBloqueado(boolean bloqueado) {
        this.bloqueado = bloqueado;
    }




}


