package hibernate;
// Generated 17-jun-2013 20:09:01 by Hibernate Tools 3.2.1.GA



/**
 * Personales generated by hbm2java
 */
public class Personal  implements java.io.Serializable {


     private Integer pkPersonal;
     private Usuarios usuarios;
     private Sucursales sucursales;
     private String nombre;
     private String ident;
     private String apellido2;
     private String apellido1;

    public Personal() {
    }

    public Personal(Usuarios usuarios, Sucursales sucursales, String nombre, String ident, String apellido2, String apellido1) {
       this.usuarios = usuarios;
       this.sucursales = sucursales;
       this.nombre = nombre;
       this.ident = ident;
       this.apellido2 = apellido2;
       this.apellido1 = apellido1;
    }
   
    public Integer getPkPersonal() {
        return this.pkPersonal;
    }
    
    public void setPkPersonal(Integer pkPersonal) {
        this.pkPersonal = pkPersonal;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public Sucursales getSucursales() {
        return this.sucursales;
    }
    
    public void setSucursales(Sucursales sucursales) {
        this.sucursales = sucursales;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getIdent() {
        return this.ident;
    }
    
    public void setIdent(String ident) {
        this.ident = ident;
    }
    public String getApellido2() {
        return this.apellido2;
    }
    
    public void setApellido2(String apellido2) {
        this.apellido2 = apellido2;
    }
    public String getApellido1() {
        return this.apellido1;
    }
    
    public void setApellido1(String apellido1) {
        this.apellido1 = apellido1;
    }




}


