package hibernate;
// Generated 19-jun-2013 14:01:36 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Sucursales generated by hbm2java
 */
public class Sucursales  implements java.io.Serializable {


     private Integer pkSucursal;
     private String nombre;
     private String direccion;
     private String cp;
     private String localidad;
     private String provincia;
     private String codigoSucursal;
     private String longitud;
     private String latitud;
     private Set personals = new HashSet(0);
     private Set clienteses = new HashSet(0);

    public Sucursales() {
    }

	
    public Sucursales(String nombre, String direccion, String cp, String localidad, String provincia, String codigoSucursal, String longitud, String latitud) {
        this.nombre = nombre;
        this.direccion = direccion;
        this.cp = cp;
        this.localidad = localidad;
        this.provincia = provincia;
        this.codigoSucursal = codigoSucursal;
        this.longitud = longitud;
        this.latitud = latitud;
    }
    public Sucursales(String nombre, String direccion, String cp, String localidad, String provincia, String codigoSucursal, String longitud, String latitud, Set personals, Set clienteses) {
       this.nombre = nombre;
       this.direccion = direccion;
       this.cp = cp;
       this.localidad = localidad;
       this.provincia = provincia;
       this.codigoSucursal = codigoSucursal;
       this.longitud = longitud;
       this.latitud = latitud;
       this.personals = personals;
       this.clienteses = clienteses;
    }
   
    public Integer getPkSucursal() {
        return this.pkSucursal;
    }
    
    public void setPkSucursal(Integer pkSucursal) {
        this.pkSucursal = pkSucursal;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getCp() {
        return this.cp;
    }
    
    public void setCp(String cp) {
        this.cp = cp;
    }
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public String getCodigoSucursal() {
        return this.codigoSucursal;
    }
    
    public void setCodigoSucursal(String codigoSucursal) {
        this.codigoSucursal = codigoSucursal;
    }
    public String getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(String longitud) {
        this.longitud = longitud;
    }
    public String getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(String latitud) {
        this.latitud = latitud;
    }
    public Set getPersonals() {
        return this.personals;
    }
    
    public void setPersonals(Set personals) {
        this.personals = personals;
    }
    public Set getClienteses() {
        return this.clienteses;
    }
    
    public void setClienteses(Set clienteses) {
        this.clienteses = clienteses;
    }




}


